name: secondFile
on :
    push:
        branches:
                -main
jobs:
    copyfile:
        runs-on: ubuntu-latest
        steps:
         - name: copy file in server
           uses: actions/checkout@v4

         - name: List files in the directory
           run: ls -la  

         - name: print directory
           run: pwd