name : build-and-test
on:
  push:
    branches:
      - feature-2
jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name : build
        run  : echo "building the project!!" > output.txt

      - name : upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output.txt

  test :
    runs-on : ubuntu-latest
    needs: build
    steps:
      - name : download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name : test
        run  : cat output.txt