name : "second yml file"
on:
  push :
    branches:
            - main
    paths:
            - '**.js'
jobs:
  js-test:
    runs-on: ubuntu-latest
    steps:
      - name: update changes
        run: echo "js file is changed !!"