name : secrets
on: 
  push:
    branches: [ fake ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env :
        MY_SECRET : ${{ secrets.MY_SECRET }}
    steps:
        - name: checking secret
          run : echo "hello $MY_SECRET"
