name : secrets
on: 
  push:
    branches: [ feature-2 ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
        - name: checking secret
          run : "hello $MY_SECRET"
          env :
            MY_SECRET : ${{secrets.MY_SECRET}}